/* GENERATED by lib/scripts/gen-og-pages.mjs — do not edit by hand.
   Route -> the isometric scene that route's social card uses, served
   from /public/og/scenes. IzRelatedRail reads this so a rail card and
   a shared link show the same drawing. Re-run the generator after
   adding or renaming a scene. */
export const SCENE_THUMB: Record<string, string> = {
  "/platform": "/og/scenes/platform.svg",
  "/solutions": "/og/scenes/solutions.svg",
  "/multifactor-authentication": "/og/scenes/multifactor-authentication.svg",
  "/zero-trust-features/single-sign-on": "/og/scenes/zero-trust-features_single-sign-on.svg",
  "/zero-trust-network-access": "/og/scenes/zero-trust-network-access.svg",
  "/zero-trust-application-access": "/og/scenes/zero-trust-application-access.svg",
  "/zero-trust-features/device-binding": "/og/scenes/zero-trust-features_device-binding.svg",
  "/zero-trust-features/device-posture-check": "/og/scenes/zero-trust-features_device-posture-check.svg",
  "/platform/endpoint-controls": "/og/scenes/platform_endpoint-controls.svg",
  "/awards": "/og/scenes/awards.svg",
  "/instasafe-newsroom": "/og/scenes/instasafe-newsroom.svg",
  "/blog": "/og/scenes/blog.svg",
  "/careers": "/og/scenes/careers.svg",
  "/resource-center": "/og/scenes/resource-center.svg",
  "/book-a-demo": "/og/scenes/book-a-demo.svg",
};
