/**
 * NEW information architecture — every route from the content-review build
 * (content-review-build.mjs output, 4 volumes), scaffolded so the whole
 * new site map routes and prerenders TODAY. Each page gets its bespoke
 * build one by one from the storyboard sheet; until then the [...slug]
 * catch-all serves these records through ScaffoldPage.
 *
 * Titles/subs are the SEO title + meta the content review carries for the
 * page. NOT in this file: /platform, /platform/iam, /solutions, /partners,
 * /book-a-demo — already routed (static routes or the legacy registry).
 *
 * This file is assembled AFTER the legacy registry and PAGES de-dupes by
 * first-wins, so an accidental path collision keeps the SEO-locked legacy
 * entry rather than silently replacing it.
 */
import type { PageDef } from "./site";

const P = (p: PageDef): PageDef => ({ ...p, desc: p.desc ?? p.sub });

export const NEW_IA: PageDef[] = [
  P({
    path: "/platform/always-on",
    kind: "platform",
    eyebrow: "Platform",
    title: "Always-On Secure Access",
    h1: "Always-On Connectivity",
    sub: "Tunnel established at boot via device certificate. No user action, no forgotten connections, no unprotected gap.",
  }),
  P({
    path: "/platform/behavioural-authentication",
    kind: "platform",
    eyebrow: "Platform",
    title: "Behavioural Authentication",
    h1: "Behavioural Authentication",
    sub: "Impersonation detection from behaviour patterns — because a stolen credential can't steal habits.",
  }),
  P({
    path: "/platform/clientless-access",
    kind: "platform",
    eyebrow: "Platform",
    title: "Clientless Remote Access",
    h1: "Clientless / Agentless Access",
    sub: "Browser-only secure access to web apps — no agent, any OS, any device. Built for third parties, BYOD, and instant scale.",
  }),
  P({
    path: "/platform/contextual-access",
    kind: "platform",
    eyebrow: "Platform",
    title: "Contextual Access Control",
    h1: "Contextual Access",
    sub: "Access decisions from context — IP, geolocation, time, device, role. The same credentials mean different things at 3 a.m. from a new country.",
  }),
  P({
    path: "/platform/device-binding",
    kind: "platform",
    eyebrow: "Platform",
    title: "Device Binding & Authorization",
    h1: "Device Authorization & Binding",
    sub: "Approve every device before first access. Certificate-bound sessions, instant revocation, admin review workflow.",
  }),
  P({
    path: "/platform/device-posture",
    kind: "platform",
    eyebrow: "Platform",
    title: "Device Posture Check",
    h1: "Device Posture Check",
    sub: "25 posture check types, 144 named rules, 1,500+ OS/device combinations. Only compliant devices connect — evaluated at login and continuously.",
  }),
  P({
    path: "/platform/domain-joining",
    kind: "platform",
    eyebrow: "Platform",
    title: "Remote Domain Joining",
    h1: "Domain Joining",
    sub: "Join remote devices to your corporate AD domain over ZTNA — push GPO, enforce compliance, no VPN and no office visit.",
  }),
  P({
    path: "/platform/endpoint-controls",
    kind: "platform",
    eyebrow: "Platform",
    title: "Endpoint Session Controls",
    h1: "Endpoint Controls",
    sub: "Clipboard control, watermarking, network and app filters, browser restrictions, inactivity timeout — session-layer DLP for remote access.",
  }),
  P({
    path: "/platform/geofencing",
    kind: "platform",
    eyebrow: "Platform",
    title: "Geofencing Access Control",
    h1: "Geofencing",
    sub: "Draw the map your access respects. Country, region, and radius conditions on every session — with drag-the-pin live demo.",
  }),
  P({
    path: "/platform/integrations",
    kind: "platform",
    eyebrow: "Platform",
    title: "Integrations",
    h1: "Integrations & Ecosystem",
    sub: "Directories, identity providers, SIEM, and the app stack — where InstaSafe plugs into what you already run.",
  }),
  P({
    path: "/platform/mfa",
    kind: "platform",
    eyebrow: "Platform",
    title: "Multi-Factor Authentication (MFA)",
    h1: "Multi-Factor Authentication",
    sub: "Six MFA methods including continuous facial authentication. Protect web apps, Windows/Linux/Mac logins, RDP, VPNs, and network devices via RADIUS and TACACS+.",
  }),
  P({
    path: "/platform/secure-browser",
    kind: "platform",
    eyebrow: "Platform",
    title: "Secure Enterprise Browser",
    h1: "Secure Enterprise Browser",
    sub: "Chromium-based browser with enterprise policy: block downloads, control clipboard, watermark screens, built-in MFA. DLP at the last inch.",
  }),
  P({
    path: "/platform/sso",
    kind: "platform",
    eyebrow: "Platform",
    title: "Single Sign-On (SSO)",
    h1: "Single Sign-On",
    sub: "One login for every provisioned app. SAML 2.0, OAuth, OpenID Connect. Built-in MFA and device binding. $[X]/user/month [PLACEHOLDER].",
  }),
  P({
    path: "/platform/trust-engine",
    kind: "platform",
    eyebrow: "Platform",
    title: "The InstaSafe Trust Engine",
    h1: "The Trust Engine (deep-dive)",
    sub: "21 policy combinations, 12 risk triggers, 4 automatic responses. The decision layer behind every InstaSafe session, explained.",
  }),
  P({
    path: "/platform/ztaa",
    kind: "platform",
    eyebrow: "Platform",
    title: "Zero Trust Application Access (ZTAA)",
    h1: "Zero Trust Application Access",
    sub: "One browser portal for web apps, RDP, SSH, VNC, databases, and file servers. Session recording, watermarking, clipboard control. Access without network exposure.",
  }),
  P({
    path: "/platform/ztna",
    kind: "platform",
    eyebrow: "Platform",
    title: "Zero Trust Network Access (ZTNA)",
    h1: "Zero Trust Network Access",
    sub: "IP-layer Zero Trust access for thick clients, legacy apps, and network protocols. Server blackening, per-session tunnels, 25 device checks. Replace VPN without re-architecture.",
  }),
  P({
    path: "/solutions/byod",
    kind: "solution",
    eyebrow: "Solutions",
    title: "BYOD Security Without MDM",
    h1: "BYOD Security",
    sub: "Personal devices, corporate access, no device seizure. Clientless portal + session controls keep data used but never kept.",
  }),
  P({
    path: "/solutions/compliance",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Compliance-Driven Access Control",
    h1: "Compliance & Regulatory",
    sub: "DPDP, RBI, SEBI, IRDAI, PCI DSS, HIPAA, ISO 27001 — the access-control evidence layer, built in.",
  }),
  P({
    path: "/solutions/database-access",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Secure Database Access",
    h1: "Secure Database Access",
    sub: "DBAs and analysts connect through identity-bound, logged sessions — not shared connection strings. PostgreSQL, MSSQL, SQL Server GA.",
  }),
  P({
    path: "/solutions/devops-security",
    kind: "solution",
    eyebrow: "Solutions",
    title: "DevOps Security | Zero Trust for Dev Teams",
    h1: "DevOps Security",
    sub: "SSH, Git, Jenkins, Jira, staging — governed and invisible to the internet, without changing how developers work.",
  }),
  P({
    path: "/solutions/hybrid-work",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Hybrid Work Security",
    h1: "Hybrid & Work-From-Home",
    sub: "The office is a location again, not a security boundary. One access model for desk, home, and everywhere between.",
  }),
  P({
    path: "/solutions/legacy-apps",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Secure Legacy App Access",
    h1: "Legacy Application Access",
    sub: "The 2009 client-server app can't do SAML. Put Zero Trust in front of it instead of inside it.",
  }),
  P({
    path: "/solutions/mergers-acquisitions",
    kind: "solution",
    eyebrow: "Solutions",
    title: "M&A IT Integration Access",
    h1: "M&A Access Integration",
    sub: "Day-one access between merging companies without merging networks. Application-level trust while the real integration takes its time.",
  }),
  P({
    path: "/solutions/privileged-access",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Privileged Access Controls",
    h1: "Privileged Access",
    sub: "Recorded, step-up-gated, time-boxed admin access to servers and consoles — the practical core of PAM through Zero Trust.",
  }),
  P({
    path: "/solutions/secure-cloud-access",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Secure Cloud Application Access",
    h1: "Secure Cloud & Multi-Cloud Access",
    sub: "One policy across on-prem, AWS, Azure, Oracle Cloud, and SaaS. Extend enterprise security to everything the cloud swallowed.",
  }),
  P({
    path: "/solutions/secure-remote-access",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Secure Remote Access",
    h1: "Secure Remote Access",
    sub: "One access model for employees, contractors, and BYOD — office, home, or field. Every app type, every device class, one policy engine.",
  }),
  P({
    path: "/solutions/secure-voip",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Secure VoIP Access",
    h1: "Secure VoIP Access",
    sub: "Zero Trust for voice — remote VoIP without VPN latency, jitter, or exposure. Privacy-first by architecture.",
  }),
  P({
    path: "/solutions/third-party-access",
    kind: "solution",
    eyebrow: "Solutions",
    title: "Third-Party & Vendor Access",
    h1: "Third-Party & Vendor Access",
    sub: "Contractors reach exactly the systems in scope — clientless, time-boxed, recorded. Access ends when the contract does.",
  }),
  P({
    path: "/solutions/vdi-alternative",
    kind: "solution",
    eyebrow: "Solutions",
    title: "VDI Alternative",
    h1: "VDI Alternative",
    sub: "Most VDI exists to solve an access problem. Solve the access problem directly — RDP/apps through a governed portal at a fraction of the operational weight.",
  }),
  P({
    path: "/solutions/vpn-alternative",
    kind: "solution",
    eyebrow: "Solutions",
    title: "VPN Alternative | Zero Trust VPN Replacement",
    h1: "VPN Alternative",
    sub: "Replace VPN with per-app Zero Trust access. No lateral movement, no backhaul latency, no hardware. Staged migration alongside your existing VPN.",
  }),
  P({
    path: "/industries/banking",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Banking & Financial Services",
    h1: "Banking & Financial Services",
    sub: "RBI-aligned access control — MFA everywhere, vendor session recording, geofenced admin access, complete audit trails. 500,000+ endpoints secured.",
  }),
  P({
    path: "/industries/bpo",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for BPO & Contact Centres",
    h1: "BPO / KPO / Contact Centres",
    sub: "Work-from-home seats with floor-grade controls — VoIP-friendly access, watermarking, per-seat attribution, and client-auditable evidence.",
  }),
  P({
    path: "/industries/education",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Education",
    h1: "Education",
    sub: "Campus systems, research data, and a population that turns over every year — access control built for churn, BYOD, and lean IT.",
  }),
  P({
    path: "/industries/energy-utilities",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Energy & Utilities",
    h1: "Energy & Utilities",
    sub: "Critical-infrastructure operators under CEA/CERT-In expectations — governed access to enterprise and plant-adjacent applications, vendor channels with replay, honest OT scope.",
  }),
  P({
    path: "/industries/fintech",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Fintech",
    h1: "Fintech",
    sub: "Move fast without exposed staging servers. Developer-speed Zero Trust — SSH, CI/CD, and production access governed, invisible, and audit-ready for partner due diligence.",
  }),
  P({
    path: "/industries/government-psu",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Government & PSUs",
    h1: "Government & PSU",
    sub: "NIST SP 800-207-aligned access for departments and public enterprises — vendor oversight, data sovereignty posture, and audit evidence at institutional scale.",
  }),
  P({
    path: "/industries/healthcare-pharma",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Healthcare & Pharma",
    h1: "Healthcare & Pharma",
    sub: "Patient data, research IP, and third-party ecosystems under least-privilege access — DPDP/HIPAA-supporting evidence built in.",
  }),
  P({
    path: "/industries/insurance",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Insurance",
    h1: "Insurance",
    sub: "IRDAI-aligned access control for insurers, brokers, and corporate agents — agent networks, TPAs, and policyholder data under one governed access model.",
  }),
  P({
    path: "/industries/it-ites",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for IT Services & ITES",
    h1: "IT / ITES",
    sub: "Client-auditable access control for delivery centres — project-scoped access, ODC-equivalent controls without the physical ODC, clean evidence for every client audit.",
  }),
  P({
    path: "/industries/manufacturing",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for Manufacturing",
    h1: "Manufacturing",
    sub: "Plant systems, OEM support access, design IP, and a multi-site workforce — governed remote access for the shop-floor era of connectivity.",
  }),
  P({
    path: "/industries/nbfc",
    kind: "industry",
    eyebrow: "Industries",
    title: "Zero Trust for NBFCs",
    h1: "NBFCs",
    sub: "RBI's NBFC cyber norms with a lean IT team — MFA, vendor control, and audit evidence without enterprise-scale overhead.",
  }),
  P({
    path: "/resources/glossary",
    kind: "resource",
    eyebrow: "Resources",
    title: "Zero Trust & Access Security Glossary",
    h1: "Zero Trust Glossary",
    sub: "40 terms, plain definitions, no jargon-defined-with-jargon. The vocabulary of modern access security.",
  }),
  P({
    path: "/resources/what-is-iam",
    kind: "resource",
    eyebrow: "Resources",
    title: "What is IAM?",
    h1: "What is IAM?",
    sub: "Identity & Access Management explained: directories, authentication, authorization and lifecycle — and how IAM feeds every zero trust access decision in InstaSafe.",
  }),
  P({
    path: "/resources/what-is-mfa",
    kind: "resource",
    eyebrow: "Resources",
    title: "What is MFA?",
    h1: "What is MFA?",
    sub: "Multi-Factor Authentication explained: factor types, where MFA belongs beyond the browser, and how InstaSafe enforces it at desktop logins, RADIUS devices and applications.",
  }),
  P({
    path: "/resources/what-is-sdp",
    kind: "resource",
    eyebrow: "Resources",
    title: "What is SDP?",
    h1: "What is SDP?",
    sub: "The Software-Defined Perimeter explained: dark infrastructure, single packet authorization and verify-then-connect — and how the SDP pattern relates to ZTNA products like InstaSafe.",
  }),
  P({
    path: "/resources/what-is-sso",
    kind: "resource",
    eyebrow: "Resources",
    title: "What is SSO?",
    h1: "What is SSO?",
    sub: "Single Sign-On explained: SAML, OAuth and OIDC in plain language, why one login beats password sprawl, and how InstaSafe SSO includes the network path, not just the app.",
  }),
  P({
    path: "/resources/what-is-zero-trust",
    kind: "resource",
    eyebrow: "Resources",
    title: "What is Zero Trust? The Complete Guide",
    h1: "What is Zero Trust?",
    sub: "Zero Trust explained from first principles — the model, the architecture (NIST SP 800-207), ZTNA vs ZTAA vs SDP, and how to actually start. No jargon required to begin.",
  }),
  P({
    path: "/resources/what-is-ztna",
    kind: "resource",
    eyebrow: "Resources",
    title: "What is ZTNA?",
    h1: "What is ZTNA?",
    sub: "Zero Trust Network Access explained: verify-then-connect access to single applications instead of network-wide VPN trust — how it works, how it differs from a VPN, and where InstaSafe fits.",
  }),
  P({
    path: "/compare",
    kind: "compare",
    eyebrow: "Company",
    title: "Compare InstaSafe | vs VPN, SASE, and Access Vendors",
    h1: "Comparison Hub",
    sub: "Honest comparisons with the criteria that matter — architecture, depth, deployment, and what happens to your data.",
  }),
  P({
    path: "/about",
    kind: "company",
    eyebrow: "Company",
    title: "About InstaSafe | Zero Trust Since 2012",
    h1: "About InstaSafe",
    sub: "Making enterprise security simple, scalable, and honest — from Bengaluru to five continents.",
  }),
  P({
    path: "/customers",
    kind: "company",
    eyebrow: "Company",
    title: "InstaSafe Customers | 500,000+ Endpoints, 5 Continents",
    h1: "Customers",
    sub: "150+ enterprises and 100+ Fortune 2000 companies run access through InstaSafe. Their words, their numbers.",
  }),
  P({
    path: "/pricing",
    kind: "company",
    eyebrow: "Company",
    title: "InstaSafe Pricing | Per-User, No Hardware",
    h1: "Pricing",
    sub: "Modular per-user pricing — SSO, MFA, or the full Zero Trust platform. No appliances, no hidden tiers.",
  }),
  P({
    path: "/trust-center",
    kind: "company",
    eyebrow: "Company",
    title: "Trust Center",
    h1: "Trust Center",
    sub: "Standards alignment, compliance mappings, security practices, and the documentation your assessment needs.",
  }),
  P({
    path: "/why-instasafe",
    kind: "company",
    eyebrow: "Company",
    title: "Why InstaSafe | Zero Trust Without the Vendor in Your Data Path",
    h1: "Why InstaSafe",
    sub: "Split-plane privacy, published console-level depth, Gartner recognition, and 13+ years of Zero Trust — the case in one page.",
  }),
  P({
    path: "/why-instasafe/privacy-first",
    kind: "company",
    eyebrow: "Company",
    title: "Privacy-First Architecture | Split-Plane Zero Trust",
    h1: "Privacy First (deep-dive)",
    sub: "Does your ZTNA vendor see your traffic? Ours can't. Control plane and data plane, separated by design — with an honest table of what we can and cannot see.",
  }),
];
